import fs from "fs-extra";
import path from "path";
import { ComposedApp } from "@app-builder/composer";

export async function writeEnvAndReadme(
  app: ComposedApp,
  outputDir: string
): Promise<void> {
  const envContent = app.env.map((key) => `${key}=`).join("\n");
  await fs.writeFile(path.join(outputDir, ".env.example"), envContent, "utf-8");

  const bucketList = app.buckets.map((b) => `- **${b.displayName}**: ${b.description ?? b.category}`).join("\n");

  const readme = `# ${app.appName}

> Generated by App Bucket Builder

## Features

${bucketList}

## Setup

\`\`\`bash
pnpm install
cp .env.example .env
# Fill in .env values

# Run database migrations
pnpm --filter @${app.appName}/db db:migrate

# Start development
pnpm dev
\`\`\`

## Apps

| App | URL |
|-----|-----|
| Frontend | http://localhost:3000 |
| API | http://localhost:3001 |

## API Routes

${app.backendRoutes.map((r) => `- \`${r}\``).join("\n")}

## Database Models

${app.dbModels.map((m) => `- \`${m}\``).join("\n")}

## Environment Variables

${app.env.map((e) => `- \`${e}\``).join("\n")}

## Deploy

### Frontend (Vercel)
\`\`\`bash
cd apps/web && vercel deploy
\`\`\`

### Backend (Railway)
\`\`\`bash
railway up
\`\`\`
`;

  await fs.writeFile(path.join(outputDir, "README.md"), readme, "utf-8");
}
